extends:
  - stylelint-config-standard
  - stylelint-config-standard-scss
  - stylelint-config-recess-order

overrides:
  - files:
      - "**/*.scss"
    customSyntax: postcss-scss

rules:
  color-hex-length: null
  declaration-block-no-duplicate-properties: true
  alpha-value-notation: number
  color-function-notation: legacy
  color-named: never
  number-max-precision: null
  declaration-no-important: null
  selector-id-pattern: null
  selector-class-pattern: null
  keyframes-name-pattern: null
  scss/at-mixin-pattern: null
  scss/dollar-variable-pattern: null
  scss/percent-placeholder-pattern: null
  scss/at-extend-no-missing-placeholder: null
